Implement Lucid REST API integration example
lucidsoftware/sample-lucid-extensions pull request #10
Opened 2023-08-03 17:05 UTC by camador-lucid

This PR implements a simple application using [NestJS](https://nestjs.com/) and integrates with Lucid's REST API.

The readme should have all the information you need to get started and run the project.
I would appreciate a look at the code just to make sure there is nothing inherently wrong.

2023-08-04 19:48 UTC, chasefreeman-lucid commented on README.md
> +Check out each subfolder to see the individual extensions and how they work.
> Check out each subfolder to see individual extensions and integrations and how they work.

2023-08-04 20:10 UTC, chasefreeman-lucid requested changes
90% of the comments are spelling errors or grammatical things I think we should clean up a bit before publishing

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/README.md
> +The application allows a user to connect their Lucid account using the [OAuth 2.0 Authenticaiton](https://developer.lucid.co/rest-api/v1/#authentication) and then request the Lucid's user profile inf
```suggestion
The application allows a user to connect their Lucid account using [OAuth 2.0 Authentication](https://developer.lucid.co/rest-api/v1/#authentication) and then request the Lucid's user profile information to display it in the UI.
```

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/README.md
> +The goal of this application is provide guidance on how you can integrate your application with Lucid. The first step to use Lucid's API is getting an OAuth 2.0 token.
```suggestion
The goal of this application is to provide guidance on how you can integrate your application with Lucid. The first step to use Lucid's API is getting an OAuth 2.0 token.
```

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/README.md
> +The behavior of this UI is powered by the [Connect script](assets/scripts/connect.js). When the button is clicked, it open a new window with the URL https://localhost:4000/oauth2/authorize
```suggestion
The behavior of this UI is powered by the [Connect script](assets/scripts/connect.js). When the button is clicked, it will open a new window with the URL https://localhost:4000/oauth2/authorize
```

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/README.md
> +Finally, the controller sends the [handle connection view](views/handleconnection.hbs) which when loaded in the popup window, will notify the connection success to the parent window. The parent windo
```suggestion
Finally, the controller sends the [handle connection view](views/handleconnection.hbs) which when loaded in the popup window, will notify the connection success to the parent window. The parent window then closes the popup and reloads the page.
```

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/README.md
> +The application `/api/profile` endpoin in the [ApiController](src/api/api.controller.ts) is responsible for getting the OAuth2 token assocaited to the logged in user, verify it has not expired or ref
```suggestion
The application `/api/profile` endpoint in the [ApiController](src/api/api.controller.ts) is responsible for getting the OAuth2 token associated to the logged in user, verifying it has not expired or refreshing it, and then using it to make the profile request.
```

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/README.md
> +The front end then, displays the profile information:
```suggestion
The front end then displays the profile information:
```

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/README.md
> +Lucid offers an extensive list APIs that you can use. Check our [documenation](https://developer.lucid.co/rest-api) for an up-to-date list.
```suggestion
Lucid offers an extensive list of APIs that you can use. Check our [documenation](https://developer.lucid.co/rest-api) for an up-to-date list.
```

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/README.md
> +1. Create a Lucid OAuth 2.0 application. Check [our documenation](https://developer.lucid.co/) for more information on how to do it.
Should this instead link to the guide for getting an oauth2 client and application here https://developer.lucid.co/guides/#oauth-2-0-client-creation?

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/README.md
> +Running the application with Docker is super simple. Run the following command to build the applicaiton docker image.
Does all of this work in multiple environments? e.g. mac vs. windows vs linux?

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/assets/scripts/connect.js
> + * If the response is a successful connection  it will close the opneded popup and reload the page.
```suggestion
 * If the response is a successful connection, it will close the opened popup and reload the page.
```

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/src/api/api.service.ts
> +   * This method performs the Get Profile request as described in https://developer.lucid.co/rest-api/v1/#get-profile86
```suggestion
   * This method performs the Get Profile request as described in https://developer.lucid.co/rest-api/v1/#get-profile
```
I don't know why it appends the 86, but it works without it and looks a little more professional

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/src/oauth2/oauth2.controller.ts
> +   * To prevent CSRF attacks, we use the  Double Submit Cookie technique using the OAuth 2.0 state parameter.
```suggestion
   * To prevent CSRF attacks, we use the Double Submit Cookie technique using the OAuth 2.0 state parameter.
```

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/src/oauth2/oauth2token.service.ts
> +   * If found, it will determine if the token has not expired and is within out lifetime threshold.
```suggestion
   * If found, it will determine if the token has not expired and is within our lifetime threshold.
```

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/src/oauth2/oauth2token.service.ts
> +   * Otherwise, it will refresh the token, store the new token inforamtion and provide the new valid access token.
```suggestion
   * Otherwise, it will refresh the token, store the new token information and provide the new valid access token.
```

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/src/oauth2/oauth2token.service.ts
> +   * @param username the app user
```suggestion
   * @param username of the app user
```

2023-08-04 20:10 UTC, chasefreeman-lucid commented on README.md
> +Check out each subfolder to see the individual extensions and how they work.
```suggestion
Check out each subfolder to see individual extensions and integrations and how they work.
```

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/README.md
> +The request will be handled by the `authorize` method in the [OAuth2Controller](src/oauth2//oauth2.controller.ts). Here we apply CSRF prevention techniques and redirect to [Lucid's authorizaiton URL]
```suggestion
The request will be handled by the `authorize` method in the [OAuth2Controller](src/oauth2//oauth2.controller.ts). Here we apply CSRF prevention techniques and redirect to [Lucid's authorization URL](https://developer.lucid.co/rest-api/v1/#access-token-endpoints). 
```

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/README.md
> +If the user grants access to the applicaiton by clicking on `Grant Access` button. This page will redirect to the provided redirect URI and will include the OAuth 2.0 auhtorization code in the query
```suggestion
If the user grants access to the application by clicking on `Grant Access` button. This page will redirect to the provided redirect URI and will include the OAuth 2.0 authorization code in the query parameters. This request is handled by the `handleRedirect` method in the [OAuth2Controller](src/oauth2//oauth2.controller.ts).
```

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/README.md
> +The controller completes the CSRF protection verification and uses the code inlcuded in the query parameter to perform the [OAuth2 token request](https://developer.lucid.co/rest-api/v1/#create-access
```suggestion
The controller completes the CSRF protection verification and uses the code included in the query parameter to perform the [OAuth2 token request](https://developer.lucid.co/rest-api/v1/#create-access-token). The obtained token is then stored and associated to the logged in user.
```

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/README.md
> +Running the application with Docker is super simple. Run the following command to build the applicaiton docker image.
```suggestion
Running the application with Docker is super simple. Run the following command to build the application docker image. 
```

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/assets/scripts/connect.js
> +   * This catch the case where the user closes the popup window
```suggestion
   * This catches the case where the user closes the popup window
```

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/src/oauth2/oauth2.controller.ts
> +   * This method directs the user to the appropiate Lucid authorization URL as described in https://developer.lucid.co/rest-api/v1/#obtaining-an-access-token
```suggestion
   * This method directs the user to the appropriate Lucid authorization URL as described in https://developer.lucid.co/rest-api/v1/#obtaining-an-access-token
```

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/src/oauth2/oauth2token.service.ts
> +  // One minutes threshold to account avoid failures due to an expired access token
```suggestion
  // One minute threshold to avoid failures due to an expired access token
```

2023-08-04 20:10 UTC, chasefreeman-lucid commented on example-rest-api-integration/src/oauth2/oauth2token.service.ts
> +   * This method will fetch the given user OAuth 2.0 token information.
```suggestion
   * This method will fetch the given user's OAuth 2.0 token information.
```

2023-08-09 15:37 UTC, camador-lucid commented on example-rest-api-integration/README.md
> +1. Create a Lucid OAuth 2.0 application. Check [our documenation](https://developer.lucid.co/) for more information on how to do it.
Yes, that is better

2023-08-09 15:38 UTC, camador-lucid commented on example-rest-api-integration/README.md
> +Running the application with Docker is super simple. Run the following command to build the applicaiton docker image.
Yes, that is the beauty of docker

2023-08-09 15:56 UTC, chasefreeman-lucid approved these changes
Looks good to me. Thanks for doing that. It looks great!

2023-08-09 17:25 UTC, merged